.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH view 1  "view " 
.SH NAME
view \- Show details of a single repository
.SH SYNOPSIS
\fBview\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Show details of a single repository
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Repository name (`namespace/repo` or bare `repo`)
