.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH setup-git 1  "setup-git " 
.SH NAME
setup\-git \- Register `nub` as a git credential helper
.SH SYNOPSIS
\fBsetup\-git\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Register `nub` as a git credential helper
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
