.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH show 1  "show " 
.SH NAME
show \- Print the current configuration and the effective host
.SH SYNOPSIS
\fBshow\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print the current configuration and the effective host
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
