.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH git-credential 1  "git-credential " 
.SH NAME
git\-credential \- Git credential protocol entry point (invoked by git, not by users)
.SH SYNOPSIS
\fBgit\-credential\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIOPERATION\fR> 
.SH DESCRIPTION
Git credential protocol entry point (invoked by git, not by users)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIOPERATION\fR>
Protocol operation requested by git
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
get: Provide credentials for a host
.IP \(bu 2
store: Persist credentials that were used successfully
.IP \(bu 2
erase: Discard credentials that were rejected
.RE
