//! Generation of the CLI reference pages from the `clap` command tree.
//!
//! `doc-gen cli` reads the `nub` command definitions through
//! [`clap::CommandFactory`], then emits one markdown page per top-level
//! subcommand under `docs/reference/cli/`, plus an index. Nested actions
//! become sections of their parent page. The output is checked in and
//! verified fresh by CI, so the reference can never drift from the parser.

use std::fmt::Write as _;

use anyhow::Result;
use clap::{Arg, ArgAction, Command, CommandFactory};

use super::{cell, page, write_or_check};

/// Directory holding the generated CLI reference pages.
const CLI_REF_DIR: &str = "docs/reference/cli";
/// Banner stamped at the top of every generated page.
const GENERATED_NOTE: &str =
    "<!-- Generated by `cargo xtask doc-gen cli`. Do not edit by hand. -->\n\n";

/// Generate (or verify with `--check`) the CLI reference pages.
pub(super) fn cli(check: bool) -> Result<()> {
    let root = nub::cli::Cli::command();

    let mut pages = vec![page(CLI_REF_DIR, "index.md", render_index(&root))];
    for sub in documented_subcommands(&root) {
        let body = format!("{GENERATED_NOTE}{}", render_command(&["nub"], 1, sub));
        pages.push(page(CLI_REF_DIR, &format!("{}.md", sub.get_name()), body));
    }

    write_or_check("cli", CLI_REF_DIR, &pages, check)
}

/// Render the CLI landing page: the program summary, the global options and a
/// table linking every top-level command.
fn render_index(root: &Command) -> String {
    let mut out = format!(
        "{GENERATED_NOTE}# CLI reference\n\n\
         These pages are generated from the `clap` command definitions by \
         `cargo xtask doc-gen cli`. Do not edit them by hand.\n\n"
    );

    if let Some(about) = root.get_about() {
        writeln!(out, "`{}`: {about}\n", root.get_name())
            .expect("writing to a String is infallible");
    }

    let globals: Vec<&Arg> = root
        .get_arguments()
        .filter(|a| is_documented(a) && a.is_global_set())
        .collect();
    if !globals.is_empty() {
        out.push_str("## Global options\n\n");
        out.push_str("| Option | Description |\n| --- | --- |\n");
        for arg in &globals {
            writeln!(out, "| {} | {} |", option_signature(arg), description(arg))
                .expect("writing to a String is infallible");
        }
        out.push('\n');
    }

    out.push_str("## Commands\n\n");
    out.push_str("| Command | Description |\n| --- | --- |\n");
    for sub in documented_subcommands(root) {
        let about = sub
            .get_about()
            .map(|a| cell(&a.to_string()))
            .unwrap_or_default();
        writeln!(out, "| [{0}]({0}.md) | {about} |", sub.get_name())
            .expect("writing to a String is infallible");
    }

    out
}

/// Render one command as a page (or, when recursing, as a section).
///
/// `path` is the chain of command names leading to this one (used for the
/// usage line). `sub` is the heading level (1 = top-level page section,
/// 2 = nested subcommand section, and so on).
fn render_command(path: &[&str], sub: usize, cmd: &Command) -> String {
    let mut out = String::new();
    let name = cmd.get_name();

    writeln!(out, "{} `{}`\n", "#".repeat(sub), name).expect("writing to a String is infallible");

    if let Some(about) = cmd.get_long_about().or_else(|| cmd.get_about()) {
        writeln!(out, "{about}\n").expect("writing to a String is infallible");
    }

    let mut full_path: Vec<&str> = path.to_vec();
    full_path.push(name);

    writeln!(out, "**Usage:** `{}`\n", usage(&full_path, cmd))
        .expect("writing to a String is infallible");

    let positionals: Vec<&Arg> = cmd.get_positionals().filter(|a| is_documented(a)).collect();
    if !positionals.is_empty() {
        writeln!(out, "{} Arguments\n", "#".repeat(sub + 1))
            .expect("writing to a String is infallible");
        out.push_str("| Argument | Description |\n| --- | --- |\n");
        for arg in &positionals {
            writeln!(
                out,
                "| `{}` | {} |",
                positional_token(arg),
                description(arg)
            )
            .expect("writing to a String is infallible");
        }
        out.push('\n');
    }

    let options: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| is_documented(a) && !a.is_positional() && !a.is_global_set())
        .collect();
    if !options.is_empty() {
        writeln!(out, "{} Options\n", "#".repeat(sub + 1))
            .expect("writing to a String is infallible");
        out.push_str("| Option | Default | Description |\n| --- | --- | --- |\n");
        for arg in &options {
            writeln!(
                out,
                "| {} | {} | {} |",
                option_signature(arg),
                default_value(arg),
                description(arg)
            )
            .expect("writing to a String is infallible");
        }
        out.push('\n');
    }

    if let Some(after) = cmd.get_after_long_help() {
        let text = after.to_string();
        let text = text.trim_end();
        if !text.is_empty() {
            writeln!(out, "{text}\n").expect("writing to a String is infallible");
        }
    }

    let subs: Vec<&Command> = documented_subcommands(cmd).collect();
    if !subs.is_empty() {
        writeln!(out, "{} Subcommands\n", "#".repeat(sub + 1))
            .expect("writing to a String is infallible");
        for s in &subs {
            writeln!(
                out,
                "- [{}](#{})",
                s.get_name(),
                s.get_name().to_lowercase()
            )
            .expect("writing to a String is infallible");
        }
        out.push('\n');
        for s in subs {
            out.push_str(&render_command(&full_path, sub + 1, s));
        }
    }

    out
}

/// The single-line usage string, deterministic.
fn usage(path: &[&str], cmd: &Command) -> String {
    let mut parts: Vec<String> = path.iter().map(|s| (*s).to_owned()).collect();
    if cmd
        .get_arguments()
        .any(|a| is_documented(a) && !a.is_positional() && !a.is_global_set())
    {
        parts.push("[OPTIONS]".to_owned());
    }
    for arg in cmd.get_positionals().filter(|a| is_documented(a)) {
        parts.push(positional_token(arg));
    }
    if documented_subcommands(cmd).next().is_some() {
        parts.push("<COMMAND>".to_owned());
    }
    parts.join(" ")
}

/// `-o, --output <OUTPUT>` (or `--force` for a flag), fenced as inline code.
fn option_signature(arg: &Arg) -> String {
    let mut flags = Vec::new();
    if let Some(short) = arg.get_short() {
        flags.push(format!("-{short}"));
    }
    if let Some(long) = arg.get_long() {
        flags.push(format!("--{long}"));
    }
    let mut sig = flags.join(", ");
    if takes_value(arg) {
        write!(sig, " <{}>", value_name(arg)).expect("writing to a String is infallible");
    }
    format!("`{sig}`")
}

/// `<TARGET>` for a required positional, `[TARGET]` for an optional one.
fn positional_token(arg: &Arg) -> String {
    let name = value_name(arg);
    if arg.is_required_set() {
        format!("<{name}>")
    } else {
        format!("[{name}]")
    }
}

/// The help text for an argument, with its possible values appended.
fn description(arg: &Arg) -> String {
    let mut text = arg
        .get_long_help()
        .or_else(|| arg.get_help())
        .map(|h| cell(&h.to_string()))
        .unwrap_or_default();

    // Only value-taking arguments carry meaningful possible values; flags
    // report a spurious `true`/`false` set that clap derives from `SetTrue`.
    if takes_value(arg) {
        let values: Vec<String> = arg
            .get_possible_values()
            .into_iter()
            .filter(|v| !v.is_hide_set())
            .map(|v| v.get_name().to_owned())
            .collect();
        if !values.is_empty() {
            if !text.is_empty() {
                text.push(' ');
            }
            write!(text, "[possible values: {}]", values.join(", "))
                .expect("writing to a String is infallible");
        }
    }
    text
}

/// The default value(s) of an option, fenced as inline code, or empty.
fn default_value(arg: &Arg) -> String {
    let defaults: Vec<String> = arg
        .get_default_values()
        .iter()
        .map(|v| v.to_string_lossy().into_owned())
        .collect();
    if defaults.is_empty() {
        String::new()
    } else {
        format!("`{}`", defaults.join(", "))
    }
}

/// The value placeholder name, from the declared value name or the upper-cased id.
fn value_name(arg: &Arg) -> String {
    arg.get_value_names()
        .and_then(<[clap::builder::Str]>::first)
        .map_or_else(|| arg.get_id().as_str().to_uppercase(), ToString::to_string)
}

/// Whether the argument consumes a value (an option) rather than being a flag.
fn takes_value(arg: &Arg) -> bool {
    !matches!(
        arg.get_action(),
        ArgAction::SetTrue
            | ArgAction::SetFalse
            | ArgAction::Count
            | ArgAction::Help
            | ArgAction::HelpShort
            | ArgAction::HelpLong
            | ArgAction::Version
    )
}

/// The visible subcommands of a command, excluding the auto-generated `help`.
fn documented_subcommands(cmd: &Command) -> impl Iterator<Item = &Command> {
    cmd.get_subcommands()
        .filter(|s| !s.is_hide_set() && s.get_name() != "help")
}

/// Whether an argument is user-facing rather than the auto `help`/`version`.
fn is_documented(arg: &Arg) -> bool {
    let id = arg.get_id().as_str();
    id != "help" && id != "version"
}
